/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BounceDataResultsInner from './BounceDataResultsInner';

/**
 * The BounceData model module.
 * @module model/BounceData
 * @version 1.0.0
 */
class BounceData {
    /**
     * Constructs a new <code>BounceData</code>.
     * @alias module:model/BounceData
     */
    constructor() { 
        
        BounceData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BounceData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BounceData} obj Optional instance to populate.
     * @return {module:model/BounceData} The populated <code>BounceData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BounceData();

            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [BounceDataResultsInner]);
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('per_page')) {
                obj['per_page'] = ApiClient.convertToType(data['per_page'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BounceData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BounceData</code>.
     */
    static validateJSON(data) {
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                BounceDataResultsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['query'] && !(typeof data['query'] === 'string' || data['query'] instanceof String)) {
            throw new Error("Expected the field `query` to be a primitive type in the JSON string but got " + data['query']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/BounceDataResultsInner>} results
 */
BounceData.prototype['results'] = undefined;

/**
 * @member {String} query
 */
BounceData.prototype['query'] = undefined;

/**
 * @member {Number} total
 */
BounceData.prototype['total'] = undefined;

/**
 * @member {Number} per_page
 */
BounceData.prototype['per_page'] = undefined;

/**
 * @member {Number} page
 */
BounceData.prototype['page'] = undefined;






export default BounceData;

