/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CampaignUpdate model module.
 * @module model/CampaignUpdate
 * @version 1.0.0
 */
class CampaignUpdate {
    /**
     * Constructs a new <code>CampaignUpdate</code>.
     * @alias module:model/CampaignUpdate
     */
    constructor() { 
        
        CampaignUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CampaignUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CampaignUpdate} obj Optional instance to populate.
     * @return {module:model/CampaignUpdate} The populated <code>CampaignUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CampaignUpdate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('lists')) {
                obj['lists'] = ApiClient.convertToType(data['lists'], ['Number']);
            }
            if (data.hasOwnProperty('from_email')) {
                obj['from_email'] = ApiClient.convertToType(data['from_email'], 'String');
            }
            if (data.hasOwnProperty('messenger')) {
                obj['messenger'] = ApiClient.convertToType(data['messenger'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('send_later')) {
                obj['send_later'] = ApiClient.convertToType(data['send_later'], 'Boolean');
            }
            if (data.hasOwnProperty('send_at')) {
                obj['send_at'] = ApiClient.convertToType(data['send_at'], Object);
            }
            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], [Object]);
            }
            if (data.hasOwnProperty('template_id')) {
                obj['template_id'] = ApiClient.convertToType(data['template_id'], 'Number');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('altbody')) {
                obj['altbody'] = ApiClient.convertToType(data['altbody'], 'String');
            }
            if (data.hasOwnProperty('archive')) {
                obj['archive'] = ApiClient.convertToType(data['archive'], 'Boolean');
            }
            if (data.hasOwnProperty('archive_template_id')) {
                obj['archive_template_id'] = ApiClient.convertToType(data['archive_template_id'], 'Number');
            }
            if (data.hasOwnProperty('archive_meta')) {
                obj['archive_meta'] = ApiClient.convertToType(data['archive_meta'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CampaignUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CampaignUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['subject'] && !(typeof data['subject'] === 'string' || data['subject'] instanceof String)) {
            throw new Error("Expected the field `subject` to be a primitive type in the JSON string but got " + data['subject']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lists'])) {
            throw new Error("Expected the field `lists` to be an array in the JSON data but got " + data['lists']);
        }
        // ensure the json data is a string
        if (data['from_email'] && !(typeof data['from_email'] === 'string' || data['from_email'] instanceof String)) {
            throw new Error("Expected the field `from_email` to be a primitive type in the JSON string but got " + data['from_email']);
        }
        // ensure the json data is a string
        if (data['messenger'] && !(typeof data['messenger'] === 'string' || data['messenger'] instanceof String)) {
            throw new Error("Expected the field `messenger` to be a primitive type in the JSON string but got " + data['messenger']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['headers'])) {
            throw new Error("Expected the field `headers` to be an array in the JSON data but got " + data['headers']);
        }
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }
        // ensure the json data is a string
        if (data['body'] && !(typeof data['body'] === 'string' || data['body'] instanceof String)) {
            throw new Error("Expected the field `body` to be a primitive type in the JSON string but got " + data['body']);
        }
        // ensure the json data is a string
        if (data['altbody'] && !(typeof data['altbody'] === 'string' || data['altbody'] instanceof String)) {
            throw new Error("Expected the field `altbody` to be a primitive type in the JSON string but got " + data['altbody']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
CampaignUpdate.prototype['name'] = undefined;

/**
 * @member {String} subject
 */
CampaignUpdate.prototype['subject'] = undefined;

/**
 * @member {Array.<Number>} lists
 */
CampaignUpdate.prototype['lists'] = undefined;

/**
 * @member {String} from_email
 */
CampaignUpdate.prototype['from_email'] = undefined;

/**
 * @member {String} messenger
 */
CampaignUpdate.prototype['messenger'] = undefined;

/**
 * @member {String} type
 */
CampaignUpdate.prototype['type'] = undefined;

/**
 * @member {Array.<String>} tags
 */
CampaignUpdate.prototype['tags'] = undefined;

/**
 * @member {Boolean} send_later
 */
CampaignUpdate.prototype['send_later'] = undefined;

/**
 * @member {Object} send_at
 */
CampaignUpdate.prototype['send_at'] = undefined;

/**
 * @member {Array.<Object>} headers
 */
CampaignUpdate.prototype['headers'] = undefined;

/**
 * @member {Number} template_id
 */
CampaignUpdate.prototype['template_id'] = undefined;

/**
 * @member {String} content_type
 */
CampaignUpdate.prototype['content_type'] = undefined;

/**
 * @member {String} body
 */
CampaignUpdate.prototype['body'] = undefined;

/**
 * @member {String} altbody
 */
CampaignUpdate.prototype['altbody'] = undefined;

/**
 * @member {Boolean} archive
 */
CampaignUpdate.prototype['archive'] = undefined;

/**
 * @member {Number} archive_template_id
 */
CampaignUpdate.prototype['archive_template_id'] = undefined;

/**
 * @member {Object} archive_meta
 */
CampaignUpdate.prototype['archive_meta'] = undefined;






export default CampaignUpdate;

