/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CampaignsCampaignIdStatusPutRequest model module.
 * @module model/CampaignsCampaignIdStatusPutRequest
 * @version 1.0.0
 */
class CampaignsCampaignIdStatusPutRequest {
    /**
     * Constructs a new <code>CampaignsCampaignIdStatusPutRequest</code>.
     * @alias module:model/CampaignsCampaignIdStatusPutRequest
     */
    constructor() { 
        
        CampaignsCampaignIdStatusPutRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CampaignsCampaignIdStatusPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CampaignsCampaignIdStatusPutRequest} obj Optional instance to populate.
     * @return {module:model/CampaignsCampaignIdStatusPutRequest} The populated <code>CampaignsCampaignIdStatusPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CampaignsCampaignIdStatusPutRequest();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CampaignsCampaignIdStatusPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CampaignsCampaignIdStatusPutRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * @member {module:model/CampaignsCampaignIdStatusPutRequest.StatusEnum} status
 */
CampaignsCampaignIdStatusPutRequest.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CampaignsCampaignIdStatusPutRequest['StatusEnum'] = {

    /**
     * value: "scheduled"
     * @const
     */
    "scheduled": "scheduled",

    /**
     * value: "running"
     * @const
     */
    "running": "running",

    /**
     * value: "paused"
     * @const
     */
    "paused": "paused",

    /**
     * value: "cancelled"
     * @const
     */
    "cancelled": "cancelled"
};



export default CampaignsCampaignIdStatusPutRequest;

