/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DashboardCountDataCampaignsByStatus from './DashboardCountDataCampaignsByStatus';

/**
 * The DashboardCountDataCampaigns model module.
 * @module model/DashboardCountDataCampaigns
 * @version 1.0.0
 */
class DashboardCountDataCampaigns {
    /**
     * Constructs a new <code>DashboardCountDataCampaigns</code>.
     * @alias module:model/DashboardCountDataCampaigns
     */
    constructor() { 
        
        DashboardCountDataCampaigns.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DashboardCountDataCampaigns</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DashboardCountDataCampaigns} obj Optional instance to populate.
     * @return {module:model/DashboardCountDataCampaigns} The populated <code>DashboardCountDataCampaigns</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DashboardCountDataCampaigns();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('by_status')) {
                obj['by_status'] = DashboardCountDataCampaignsByStatus.constructFromObject(data['by_status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DashboardCountDataCampaigns</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DashboardCountDataCampaigns</code>.
     */
    static validateJSON(data) {
        // validate the optional field `by_status`
        if (data['by_status']) { // data not null
          DashboardCountDataCampaignsByStatus.validateJSON(data['by_status']);
        }

        return true;
    }


}



/**
 * @member {Number} total
 */
DashboardCountDataCampaigns.prototype['total'] = undefined;

/**
 * @member {module:model/DashboardCountDataCampaignsByStatus} by_status
 */
DashboardCountDataCampaigns.prototype['by_status'] = undefined;






export default DashboardCountDataCampaigns;

