/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DashboardCountDataSubscribers model module.
 * @module model/DashboardCountDataSubscribers
 * @version 1.0.0
 */
class DashboardCountDataSubscribers {
    /**
     * Constructs a new <code>DashboardCountDataSubscribers</code>.
     * @alias module:model/DashboardCountDataSubscribers
     */
    constructor() { 
        
        DashboardCountDataSubscribers.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DashboardCountDataSubscribers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DashboardCountDataSubscribers} obj Optional instance to populate.
     * @return {module:model/DashboardCountDataSubscribers} The populated <code>DashboardCountDataSubscribers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DashboardCountDataSubscribers();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('blocklisted')) {
                obj['blocklisted'] = ApiClient.convertToType(data['blocklisted'], Object);
            }
            if (data.hasOwnProperty('orphans')) {
                obj['orphans'] = ApiClient.convertToType(data['orphans'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DashboardCountDataSubscribers</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DashboardCountDataSubscribers</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} total
 */
DashboardCountDataSubscribers.prototype['total'] = undefined;

/**
 * @member {Object} blocklisted
 */
DashboardCountDataSubscribers.prototype['blocklisted'] = undefined;

/**
 * @member {Number} orphans
 */
DashboardCountDataSubscribers.prototype['orphans'] = undefined;






export default DashboardCountDataSubscribers;

