/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DashboardCountDataLists model module.
 * @module model/DashboardCountDataLists
 * @version 1.0.0
 */
class DashboardCountDataLists {
    /**
     * Constructs a new <code>DashboardCountDataLists</code>.
     * @alias module:model/DashboardCountDataLists
     */
    constructor() { 
        
        DashboardCountDataLists.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DashboardCountDataLists</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DashboardCountDataLists} obj Optional instance to populate.
     * @return {module:model/DashboardCountDataLists} The populated <code>DashboardCountDataLists</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DashboardCountDataLists();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('private')) {
                obj['private'] = ApiClient.convertToType(data['private'], 'Number');
            }
            if (data.hasOwnProperty('public')) {
                obj['public'] = ApiClient.convertToType(data['public'], 'Number');
            }
            if (data.hasOwnProperty('optin_single')) {
                obj['optin_single'] = ApiClient.convertToType(data['optin_single'], 'Number');
            }
            if (data.hasOwnProperty('optin_double')) {
                obj['optin_double'] = ApiClient.convertToType(data['optin_double'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DashboardCountDataLists</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DashboardCountDataLists</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} total
 */
DashboardCountDataLists.prototype['total'] = undefined;

/**
 * @member {Number} private
 */
DashboardCountDataLists.prototype['private'] = undefined;

/**
 * @member {Number} public
 */
DashboardCountDataLists.prototype['public'] = undefined;

/**
 * @member {Number} optin_single
 */
DashboardCountDataLists.prototype['optin_single'] = undefined;

/**
 * @member {Number} optin_double
 */
DashboardCountDataLists.prototype['optin_double'] = undefined;






export default DashboardCountDataLists;

