/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DashboardCountDataCampaigns from './DashboardCountDataCampaigns';
import DashboardCountDataLists from './DashboardCountDataLists';
import DashboardCountDataSubscribers from './DashboardCountDataSubscribers';

/**
 * The DashboardCountData model module.
 * @module model/DashboardCountData
 * @version 1.0.0
 */
class DashboardCountData {
    /**
     * Constructs a new <code>DashboardCountData</code>.
     * @alias module:model/DashboardCountData
     */
    constructor() { 
        
        DashboardCountData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DashboardCountData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DashboardCountData} obj Optional instance to populate.
     * @return {module:model/DashboardCountData} The populated <code>DashboardCountData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DashboardCountData();

            if (data.hasOwnProperty('subscribers')) {
                obj['subscribers'] = DashboardCountDataSubscribers.constructFromObject(data['subscribers']);
            }
            if (data.hasOwnProperty('lists')) {
                obj['lists'] = DashboardCountDataLists.constructFromObject(data['lists']);
            }
            if (data.hasOwnProperty('campaigns')) {
                obj['campaigns'] = DashboardCountDataCampaigns.constructFromObject(data['campaigns']);
            }
            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DashboardCountData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DashboardCountData</code>.
     */
    static validateJSON(data) {
        // validate the optional field `subscribers`
        if (data['subscribers']) { // data not null
          DashboardCountDataSubscribers.validateJSON(data['subscribers']);
        }
        // validate the optional field `lists`
        if (data['lists']) { // data not null
          DashboardCountDataLists.validateJSON(data['lists']);
        }
        // validate the optional field `campaigns`
        if (data['campaigns']) { // data not null
          DashboardCountDataCampaigns.validateJSON(data['campaigns']);
        }

        return true;
    }


}



/**
 * @member {module:model/DashboardCountDataSubscribers} subscribers
 */
DashboardCountData.prototype['subscribers'] = undefined;

/**
 * @member {module:model/DashboardCountDataLists} lists
 */
DashboardCountData.prototype['lists'] = undefined;

/**
 * @member {module:model/DashboardCountDataCampaigns} campaigns
 */
DashboardCountData.prototype['campaigns'] = undefined;

/**
 * @member {Number} messages
 */
DashboardCountData.prototype['messages'] = undefined;






export default DashboardCountData;

