/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LanguagePackData from './LanguagePackData';

/**
 * The LanguagePack model module.
 * @module model/LanguagePack
 * @version 1.0.0
 */
class LanguagePack {
    /**
     * Constructs a new <code>LanguagePack</code>.
     * @alias module:model/LanguagePack
     */
    constructor() { 
        
        LanguagePack.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LanguagePack</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LanguagePack} obj Optional instance to populate.
     * @return {module:model/LanguagePack} The populated <code>LanguagePack</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LanguagePack();

            if (data.hasOwnProperty('data')) {
                obj['data'] = LanguagePackData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LanguagePack</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LanguagePack</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          LanguagePackData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/LanguagePackData} data
 */
LanguagePack.prototype['data'] = undefined;






export default LanguagePack;

