/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MailBoxBounces model module.
 * @module model/MailBoxBounces
 * @version 1.0.0
 */
class MailBoxBounces {
    /**
     * Constructs a new <code>MailBoxBounces</code>.
     * @alias module:model/MailBoxBounces
     */
    constructor() { 
        
        MailBoxBounces.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MailBoxBounces</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MailBoxBounces} obj Optional instance to populate.
     * @return {module:model/MailBoxBounces} The populated <code>MailBoxBounces</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MailBoxBounces();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('auth_protocol')) {
                obj['auth_protocol'] = ApiClient.convertToType(data['auth_protocol'], 'String');
            }
            if (data.hasOwnProperty('return_path')) {
                obj['return_path'] = ApiClient.convertToType(data['return_path'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('tls_enabled')) {
                obj['tls_enabled'] = ApiClient.convertToType(data['tls_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('tls_skip_verify')) {
                obj['tls_skip_verify'] = ApiClient.convertToType(data['tls_skip_verify'], 'Boolean');
            }
            if (data.hasOwnProperty('scan_interval')) {
                obj['scan_interval'] = ApiClient.convertToType(data['scan_interval'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MailBoxBounces</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MailBoxBounces</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }
        // ensure the json data is a string
        if (data['auth_protocol'] && !(typeof data['auth_protocol'] === 'string' || data['auth_protocol'] instanceof String)) {
            throw new Error("Expected the field `auth_protocol` to be a primitive type in the JSON string but got " + data['auth_protocol']);
        }
        // ensure the json data is a string
        if (data['return_path'] && !(typeof data['return_path'] === 'string' || data['return_path'] instanceof String)) {
            throw new Error("Expected the field `return_path` to be a primitive type in the JSON string but got " + data['return_path']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['scan_interval'] && !(typeof data['scan_interval'] === 'string' || data['scan_interval'] instanceof String)) {
            throw new Error("Expected the field `scan_interval` to be a primitive type in the JSON string but got " + data['scan_interval']);
        }

        return true;
    }


}



/**
 * @member {String} uuid
 */
MailBoxBounces.prototype['uuid'] = undefined;

/**
 * @member {Boolean} enabled
 */
MailBoxBounces.prototype['enabled'] = undefined;

/**
 * @member {String} type
 */
MailBoxBounces.prototype['type'] = undefined;

/**
 * @member {String} host
 */
MailBoxBounces.prototype['host'] = undefined;

/**
 * @member {Number} port
 */
MailBoxBounces.prototype['port'] = undefined;

/**
 * @member {String} auth_protocol
 */
MailBoxBounces.prototype['auth_protocol'] = undefined;

/**
 * @member {String} return_path
 */
MailBoxBounces.prototype['return_path'] = undefined;

/**
 * @member {String} username
 */
MailBoxBounces.prototype['username'] = undefined;

/**
 * @member {Boolean} tls_enabled
 */
MailBoxBounces.prototype['tls_enabled'] = undefined;

/**
 * @member {Boolean} tls_skip_verify
 */
MailBoxBounces.prototype['tls_skip_verify'] = undefined;

/**
 * @member {String} scan_interval
 */
MailBoxBounces.prototype['scan_interval'] = undefined;






export default MailBoxBounces;

