/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MediaFileObject model module.
 * @module model/MediaFileObject
 * @version 1.0.0
 */
class MediaFileObject {
    /**
     * Constructs a new <code>MediaFileObject</code>.
     * @alias module:model/MediaFileObject
     */
    constructor() { 
        
        MediaFileObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MediaFileObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MediaFileObject} obj Optional instance to populate.
     * @return {module:model/MediaFileObject} The populated <code>MediaFileObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MediaFileObject();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('thumb_uri')) {
                obj['thumb_uri'] = ApiClient.convertToType(data['thumb_uri'], 'String');
            }
            if (data.hasOwnProperty('uri')) {
                obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MediaFileObject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MediaFileObject</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['filename'] && !(typeof data['filename'] === 'string' || data['filename'] instanceof String)) {
            throw new Error("Expected the field `filename` to be a primitive type in the JSON string but got " + data['filename']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['thumb_uri'] && !(typeof data['thumb_uri'] === 'string' || data['thumb_uri'] instanceof String)) {
            throw new Error("Expected the field `thumb_uri` to be a primitive type in the JSON string but got " + data['thumb_uri']);
        }
        // ensure the json data is a string
        if (data['uri'] && !(typeof data['uri'] === 'string' || data['uri'] instanceof String)) {
            throw new Error("Expected the field `uri` to be a primitive type in the JSON string but got " + data['uri']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
MediaFileObject.prototype['id'] = undefined;

/**
 * @member {String} uuid
 */
MediaFileObject.prototype['uuid'] = undefined;

/**
 * @member {String} filename
 */
MediaFileObject.prototype['filename'] = undefined;

/**
 * @member {String} created_at
 */
MediaFileObject.prototype['created_at'] = undefined;

/**
 * @member {String} thumb_uri
 */
MediaFileObject.prototype['thumb_uri'] = undefined;

/**
 * @member {String} uri
 */
MediaFileObject.prototype['uri'] = undefined;






export default MediaFileObject;

