/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BounceDataResultsInnerCampaign from './BounceDataResultsInnerCampaign';

/**
 * The NewCampaignData model module.
 * @module model/NewCampaignData
 * @version 1.0.0
 */
class NewCampaignData {
    /**
     * Constructs a new <code>NewCampaignData</code>.
     * @alias module:model/NewCampaignData
     */
    constructor() { 
        
        NewCampaignData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NewCampaignData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewCampaignData} obj Optional instance to populate.
     * @return {module:model/NewCampaignData} The populated <code>NewCampaignData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewCampaignData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('views')) {
                obj['views'] = ApiClient.convertToType(data['views'], 'Number');
            }
            if (data.hasOwnProperty('clicks')) {
                obj['clicks'] = ApiClient.convertToType(data['clicks'], 'Number');
            }
            if (data.hasOwnProperty('bounces')) {
                obj['bounces'] = ApiClient.convertToType(data['bounces'], 'Number');
            }
            if (data.hasOwnProperty('lists')) {
                obj['lists'] = ApiClient.convertToType(data['lists'], [BounceDataResultsInnerCampaign]);
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'String');
            }
            if (data.hasOwnProperty('to_send')) {
                obj['to_send'] = ApiClient.convertToType(data['to_send'], 'Number');
            }
            if (data.hasOwnProperty('sent')) {
                obj['sent'] = ApiClient.convertToType(data['sent'], 'Number');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('from_email')) {
                obj['from_email'] = ApiClient.convertToType(data['from_email'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('altbody')) {
                obj['altbody'] = ApiClient.convertToType(data['altbody'], 'String');
            }
            if (data.hasOwnProperty('send_at')) {
                obj['send_at'] = ApiClient.convertToType(data['send_at'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('template_id')) {
                obj['template_id'] = ApiClient.convertToType(data['template_id'], 'Number');
            }
            if (data.hasOwnProperty('messenger')) {
                obj['messenger'] = ApiClient.convertToType(data['messenger'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NewCampaignData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NewCampaignData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }
        if (data['lists']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['lists'])) {
                throw new Error("Expected the field `lists` to be an array in the JSON data but got " + data['lists']);
            }
            // validate the optional field `lists` (array)
            for (const item of data['lists']) {
                BounceDataResultsInnerCampaign.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['started_at'] && !(typeof data['started_at'] === 'string' || data['started_at'] instanceof String)) {
            throw new Error("Expected the field `started_at` to be a primitive type in the JSON string but got " + data['started_at']);
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['subject'] && !(typeof data['subject'] === 'string' || data['subject'] instanceof String)) {
            throw new Error("Expected the field `subject` to be a primitive type in the JSON string but got " + data['subject']);
        }
        // ensure the json data is a string
        if (data['from_email'] && !(typeof data['from_email'] === 'string' || data['from_email'] instanceof String)) {
            throw new Error("Expected the field `from_email` to be a primitive type in the JSON string but got " + data['from_email']);
        }
        // ensure the json data is a string
        if (data['body'] && !(typeof data['body'] === 'string' || data['body'] instanceof String)) {
            throw new Error("Expected the field `body` to be a primitive type in the JSON string but got " + data['body']);
        }
        // ensure the json data is a string
        if (data['altbody'] && !(typeof data['altbody'] === 'string' || data['altbody'] instanceof String)) {
            throw new Error("Expected the field `altbody` to be a primitive type in the JSON string but got " + data['altbody']);
        }
        // ensure the json data is a string
        if (data['send_at'] && !(typeof data['send_at'] === 'string' || data['send_at'] instanceof String)) {
            throw new Error("Expected the field `send_at` to be a primitive type in the JSON string but got " + data['send_at']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }
        // ensure the json data is a string
        if (data['messenger'] && !(typeof data['messenger'] === 'string' || data['messenger'] instanceof String)) {
            throw new Error("Expected the field `messenger` to be a primitive type in the JSON string but got " + data['messenger']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
NewCampaignData.prototype['id'] = undefined;

/**
 * @member {String} created_at
 */
NewCampaignData.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
NewCampaignData.prototype['updated_at'] = undefined;

/**
 * @member {Number} views
 */
NewCampaignData.prototype['views'] = undefined;

/**
 * @member {Number} clicks
 */
NewCampaignData.prototype['clicks'] = undefined;

/**
 * @member {Number} bounces
 */
NewCampaignData.prototype['bounces'] = undefined;

/**
 * @member {Array.<module:model/BounceDataResultsInnerCampaign>} lists
 */
NewCampaignData.prototype['lists'] = undefined;

/**
 * @member {String} started_at
 */
NewCampaignData.prototype['started_at'] = undefined;

/**
 * @member {Number} to_send
 */
NewCampaignData.prototype['to_send'] = undefined;

/**
 * @member {Number} sent
 */
NewCampaignData.prototype['sent'] = undefined;

/**
 * @member {String} uuid
 */
NewCampaignData.prototype['uuid'] = undefined;

/**
 * @member {String} type
 */
NewCampaignData.prototype['type'] = undefined;

/**
 * @member {String} name
 */
NewCampaignData.prototype['name'] = undefined;

/**
 * @member {String} subject
 */
NewCampaignData.prototype['subject'] = undefined;

/**
 * @member {String} from_email
 */
NewCampaignData.prototype['from_email'] = undefined;

/**
 * @member {String} body
 */
NewCampaignData.prototype['body'] = undefined;

/**
 * @member {String} altbody
 */
NewCampaignData.prototype['altbody'] = undefined;

/**
 * @member {String} send_at
 */
NewCampaignData.prototype['send_at'] = undefined;

/**
 * @member {String} status
 */
NewCampaignData.prototype['status'] = undefined;

/**
 * @member {String} content_type
 */
NewCampaignData.prototype['content_type'] = undefined;

/**
 * @member {Array.<String>} tags
 */
NewCampaignData.prototype['tags'] = undefined;

/**
 * @member {Number} template_id
 */
NewCampaignData.prototype['template_id'] = undefined;

/**
 * @member {String} messenger
 */
NewCampaignData.prototype['messenger'] = undefined;






export default NewCampaignData;

