/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PublicSubscriptionPost200Response model module.
 * @module model/PublicSubscriptionPost200Response
 * @version 1.0.0
 */
class PublicSubscriptionPost200Response {
    /**
     * Constructs a new <code>PublicSubscriptionPost200Response</code>.
     * @alias module:model/PublicSubscriptionPost200Response
     */
    constructor() { 
        
        PublicSubscriptionPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PublicSubscriptionPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicSubscriptionPost200Response} obj Optional instance to populate.
     * @return {module:model/PublicSubscriptionPost200Response} The populated <code>PublicSubscriptionPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicSubscriptionPost200Response();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('list_uuids')) {
                obj['list_uuids'] = ApiClient.convertToType(data['list_uuids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PublicSubscriptionPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PublicSubscriptionPost200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['list_uuids'])) {
            throw new Error("Expected the field `list_uuids` to be an array in the JSON data but got " + data['list_uuids']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
PublicSubscriptionPost200Response.prototype['name'] = undefined;

/**
 * @member {String} email
 */
PublicSubscriptionPost200Response.prototype['email'] = undefined;

/**
 * @member {Array.<String>} list_uuids
 */
PublicSubscriptionPost200Response.prototype['list_uuids'] = undefined;






export default PublicSubscriptionPost200Response;

