/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubscriberProfileAttribs model module.
 * @module model/SubscriberProfileAttribs
 * @version 1.0.0
 */
class SubscriberProfileAttribs {
    /**
     * Constructs a new <code>SubscriberProfileAttribs</code>.
     * @alias module:model/SubscriberProfileAttribs
     */
    constructor() { 
        
        SubscriberProfileAttribs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubscriberProfileAttribs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriberProfileAttribs} obj Optional instance to populate.
     * @return {module:model/SubscriberProfileAttribs} The populated <code>SubscriberProfileAttribs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriberProfileAttribs();

            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('good')) {
                obj['good'] = ApiClient.convertToType(data['good'], 'Boolean');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriberProfileAttribs</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriberProfileAttribs</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}



/**
 * @member {String} city
 */
SubscriberProfileAttribs.prototype['city'] = undefined;

/**
 * @member {Boolean} good
 */
SubscriberProfileAttribs.prototype['good'] = undefined;

/**
 * @member {String} type
 */
SubscriberProfileAttribs.prototype['type'] = undefined;






export default SubscriberProfileAttribs;

