/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubscriberRegistrationInfoAttribs from './SubscriberRegistrationInfoAttribs';

/**
 * The SubscriberRegistrationInfo model module.
 * @module model/SubscriberRegistrationInfo
 * @version 1.0.0
 */
class SubscriberRegistrationInfo {
    /**
     * Constructs a new <code>SubscriberRegistrationInfo</code>.
     * @alias module:model/SubscriberRegistrationInfo
     */
    constructor() { 
        
        SubscriberRegistrationInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubscriberRegistrationInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriberRegistrationInfo} obj Optional instance to populate.
     * @return {module:model/SubscriberRegistrationInfo} The populated <code>SubscriberRegistrationInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriberRegistrationInfo();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('lists')) {
                obj['lists'] = ApiClient.convertToType(data['lists'], ['Number']);
            }
            if (data.hasOwnProperty('attribs')) {
                obj['attribs'] = SubscriberRegistrationInfoAttribs.constructFromObject(data['attribs']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriberRegistrationInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriberRegistrationInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['lists'])) {
            throw new Error("Expected the field `lists` to be an array in the JSON data but got " + data['lists']);
        }
        // validate the optional field `attribs`
        if (data['attribs']) { // data not null
          SubscriberRegistrationInfoAttribs.validateJSON(data['attribs']);
        }

        return true;
    }


}



/**
 * @member {String} email
 */
SubscriberRegistrationInfo.prototype['email'] = undefined;

/**
 * @member {String} name
 */
SubscriberRegistrationInfo.prototype['name'] = undefined;

/**
 * @member {String} status
 */
SubscriberRegistrationInfo.prototype['status'] = undefined;

/**
 * @member {Array.<Number>} lists
 */
SubscriberRegistrationInfo.prototype['lists'] = undefined;

/**
 * @member {module:model/SubscriberRegistrationInfoAttribs} attribs
 */
SubscriberRegistrationInfo.prototype['attribs'] = undefined;






export default SubscriberRegistrationInfo;

