/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubscriberRegistrationInfoAttribsStack model module.
 * @module model/SubscriberRegistrationInfoAttribsStack
 * @version 1.0.0
 */
class SubscriberRegistrationInfoAttribsStack {
    /**
     * Constructs a new <code>SubscriberRegistrationInfoAttribsStack</code>.
     * @alias module:model/SubscriberRegistrationInfoAttribsStack
     */
    constructor() { 
        
        SubscriberRegistrationInfoAttribsStack.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubscriberRegistrationInfoAttribsStack</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriberRegistrationInfoAttribsStack} obj Optional instance to populate.
     * @return {module:model/SubscriberRegistrationInfoAttribsStack} The populated <code>SubscriberRegistrationInfoAttribsStack</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriberRegistrationInfoAttribsStack();

            if (data.hasOwnProperty('languages')) {
                obj['languages'] = ApiClient.convertToType(data['languages'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriberRegistrationInfoAttribsStack</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriberRegistrationInfoAttribsStack</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['languages'])) {
            throw new Error("Expected the field `languages` to be an array in the JSON data but got " + data['languages']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} languages
 */
SubscriberRegistrationInfoAttribsStack.prototype['languages'] = undefined;






export default SubscriberRegistrationInfoAttribsStack;

