/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Listmonk);
  }
}(this, function(expect, Listmonk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Listmonk.BounceDataResultsInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BounceDataResultsInner', function() {
    it('should create an instance of BounceDataResultsInner', function() {
      // uncomment below and update the code to test BounceDataResultsInner
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be.a(Listmonk.BounceDataResultsInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

    it('should have the property meta (base name: "meta")', function() {
      // uncomment below and update the code to test the property meta
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

    it('should have the property subscriberUuid (base name: "subscriber_uuid")', function() {
      // uncomment below and update the code to test the property subscriberUuid
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

    it('should have the property subscriberId (base name: "subscriber_id")', function() {
      // uncomment below and update the code to test the property subscriberId
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

    it('should have the property campaign (base name: "campaign")', function() {
      // uncomment below and update the code to test the property campaign
      //var instance = new Listmonk.BounceDataResultsInner();
      //expect(instance).to.be();
    });

  });

}));
