/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Listmonk);
  }
}(this, function(expect, Listmonk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Listmonk.MailBoxBounces();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MailBoxBounces', function() {
    it('should create an instance of MailBoxBounces', function() {
      // uncomment below and update the code to test MailBoxBounces
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be.a(Listmonk.MailBoxBounces);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property host (base name: "host")', function() {
      // uncomment below and update the code to test the property host
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property port (base name: "port")', function() {
      // uncomment below and update the code to test the property port
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property authProtocol (base name: "auth_protocol")', function() {
      // uncomment below and update the code to test the property authProtocol
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property returnPath (base name: "return_path")', function() {
      // uncomment below and update the code to test the property returnPath
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property tlsEnabled (base name: "tls_enabled")', function() {
      // uncomment below and update the code to test the property tlsEnabled
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property tlsSkipVerify (base name: "tls_skip_verify")', function() {
      // uncomment below and update the code to test the property tlsSkipVerify
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

    it('should have the property scanInterval (base name: "scan_interval")', function() {
      // uncomment below and update the code to test the property scanInterval
      //var instance = new Listmonk.MailBoxBounces();
      //expect(instance).to.be();
    });

  });

}));
