/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Listmonk);
  }
}(this, function(expect, Listmonk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Listmonk.SMTPSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SMTPSettings', function() {
    it('should create an instance of SMTPSettings', function() {
      // uncomment below and update the code to test SMTPSettings
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be.a(Listmonk.SMTPSettings);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property host (base name: "host")', function() {
      // uncomment below and update the code to test the property host
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property helloHostname (base name: "hello_hostname")', function() {
      // uncomment below and update the code to test the property helloHostname
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property port (base name: "port")', function() {
      // uncomment below and update the code to test the property port
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property authProtocol (base name: "auth_protocol")', function() {
      // uncomment below and update the code to test the property authProtocol
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property emailHeaders (base name: "email_headers")', function() {
      // uncomment below and update the code to test the property emailHeaders
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property maxConns (base name: "max_conns")', function() {
      // uncomment below and update the code to test the property maxConns
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property maxMsgRetries (base name: "max_msg_retries")', function() {
      // uncomment below and update the code to test the property maxMsgRetries
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property idleTimeout (base name: "idle_timeout")', function() {
      // uncomment below and update the code to test the property idleTimeout
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property waitTimeout (base name: "wait_timeout")', function() {
      // uncomment below and update the code to test the property waitTimeout
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property tlsType (base name: "tls_type")', function() {
      // uncomment below and update the code to test the property tlsType
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

    it('should have the property tlsSkipVerify (base name: "tls_skip_verify")', function() {
      // uncomment below and update the code to test the property tlsSkipVerify
      //var instance = new Listmonk.SMTPSettings();
      //expect(instance).to.be();
    });

  });

}));
