/**
 * Listmonk
 * The API collection for listmonk
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Listmonk);
  }
}(this, function(expect, Listmonk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Listmonk.CampaignsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CampaignsApi', function() {
    describe('campaignsCampaignIdContentPost', function() {
      it('should call campaignsCampaignIdContentPost successfully', function(done) {
        //uncomment below and update the code to test campaignsCampaignIdContentPost
        //instance.campaignsCampaignIdContentPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsCampaignIdDelete', function() {
      it('should call campaignsCampaignIdDelete successfully', function(done) {
        //uncomment below and update the code to test campaignsCampaignIdDelete
        //instance.campaignsCampaignIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsCampaignIdGet', function() {
      it('should call campaignsCampaignIdGet successfully', function(done) {
        //uncomment below and update the code to test campaignsCampaignIdGet
        //instance.campaignsCampaignIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsCampaignIdPreviewGet', function() {
      it('should call campaignsCampaignIdPreviewGet successfully', function(done) {
        //uncomment below and update the code to test campaignsCampaignIdPreviewGet
        //instance.campaignsCampaignIdPreviewGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsCampaignIdPut', function() {
      it('should call campaignsCampaignIdPut successfully', function(done) {
        //uncomment below and update the code to test campaignsCampaignIdPut
        //instance.campaignsCampaignIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsCampaignIdStatusPut', function() {
      it('should call campaignsCampaignIdStatusPut successfully', function(done) {
        //uncomment below and update the code to test campaignsCampaignIdStatusPut
        //instance.campaignsCampaignIdStatusPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsCampaignIdTestPost', function() {
      it('should call campaignsCampaignIdTestPost successfully', function(done) {
        //uncomment below and update the code to test campaignsCampaignIdTestPost
        //instance.campaignsCampaignIdTestPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsCampaignIdTextGet', function() {
      it('should call campaignsCampaignIdTextGet successfully', function(done) {
        //uncomment below and update the code to test campaignsCampaignIdTextGet
        //instance.campaignsCampaignIdTextGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsGet', function() {
      it('should call campaignsGet successfully', function(done) {
        //uncomment below and update the code to test campaignsGet
        //instance.campaignsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsPost', function() {
      it('should call campaignsPost successfully', function(done) {
        //uncomment below and update the code to test campaignsPost
        //instance.campaignsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('campaignsRunningStatsGet', function() {
      it('should call campaignsRunningStatsGet successfully', function(done) {
        //uncomment below and update the code to test campaignsRunningStatsGet
        //instance.campaignsRunningStatsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
